<?php
return array (
  'tefuir' => 
  array (
    'status' => '1',
    'from' => 'tefuir',
    'show' => '小七专线',
    'des' => '',
    'ps' => '0',
    'parse' => '',
    'parse2' => '',
    'sort' => '9999999',
    'tip' => '',
    'kernel' => '0',
    'features' => '.*?\\.mp4',
    'headers' => '',
    'issethead' => '',
    'id' => 'tefuir',
  ),
  'tkm3u8' => 
  array (
    'status' => '1',
    'from' => 'tkm3u8',
    'show' => '天空在线',
    'des' => '',
    'ps' => '0',
    'parse' => '',
    'parse2' => '',
    'sort' => '6',
    'tip' => '',
    'kernel' => '0',
    'features' => '.*?\\.m3u8',
    'headers' => '',
    'issethead' => '',
  ),
  'bjm3u8' => 
  array (
    'status' => '1',
    'from' => 'bjm3u8',
    'show' => '八戒在线',
    'des' => '',
    'ps' => '0',
    'parse' => '',
    'parse2' => '',
    'sort' => '2',
    'tip' => '',
    'kernel' => '0',
    'features' => '.*?\\.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'bjm3u8',
  ),
  'dbmu3u8' => 
  array (
    'status' => '1',
    'from' => 'dbmu3u8',
    'show' => '百度在线',
    'des' => '',
    'ps' => '0',
    'parse' => '',
    'parse2' => '',
    'sort' => '1',
    'tip' => '',
    'kernel' => '0',
    'features' => '.*?\\.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'dbmu3u8',
  ),
  'iqiyi' => 
  array (
    'status' => '1',
    'from' => 'iqiyi',
    'show' => '爱奇艺',
    'des' => '',
    'ps' => '1',
    'parse' => '',
    'parse2' => 'http://ql..sgys9.com/home/api?type=ys&uid=237120&key=pqtuwCFJOPQRVWX279&url=',
    'sort' => '',
    'tip' => '',
    'kernel' => '0',
    'features' => '',
    'headers' => '',
    'issethead' => '',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果TV',
    'des' => '',
    'ps' => '1',
    'parse' => '',
    'parse2' => 'http://ql..sgys9.com/home/api?type=ys&uid=237120&key=pqtuwCFJOPQRVWX279&url=',
    'sort' => '',
    'tip' => '',
    'kernel' => '0',
    'features' => '',
    'headers' => '',
    'issethead' => '',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => '',
    'ps' => '1',
    'parse' => '',
    'parse2' => 'http://ql..sgys9.com/home/api?type=ys&uid=237120&key=pqtuwCFJOPQRVWX279&url=',
    'sort' => '',
    'tip' => '',
    'kernel' => '0',
    'features' => '',
    'headers' => '',
    'issethead' => '',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷',
    'des' => '',
    'ps' => '1',
    'parse' => '',
    'parse2' => 'http://ql..sgys9.com/home/api?type=ys&uid=237120&key=pqtuwCFJOPQRVWX279&url=',
    'sort' => '',
    'tip' => '',
    'kernel' => '0',
    'features' => '',
    'headers' => '',
    'issethead' => '',
  ),
);